# Generated by Django 4.1.6 on 2023-02-11 13:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0005_alter_authors_born_date_alter_authors_born_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.ForeignKey(default='!No autor yet!', on_delete=django.db.models.deletion.CASCADE, to='app_quotes.authors'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='!No autor yet!', max_length=100), size=15), size=15),
        ),
    ]
