# Generated by Django 4.1.6 on 2023-02-11 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0007_alter_quotes_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=15), default='(!{No tags!}', size=15),
        ),
    ]
