# Generated by Django 4.1.6 on 2023-02-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0010_alter_quotes_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='born_date',
            field=models.CharField(default='No born data.', max_length=50),
        ),
        migrations.AlterField(
            model_name='authors',
            name='born_location',
            field=models.CharField(default='No born data.', max_length=250),
        ),
        migrations.AlterField(
            model_name='authors',
            name='description',
            field=models.CharField(default='No description.', max_length=5000),
        ),
    ]
