# Generated by Django 4.1.6 on 2023-02-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0011_alter_authors_born_date_alter_authors_born_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quotes.authors'),
        ),
    ]
